### PR TITLE
Add ddd macros

### PR DESCRIPTION
**Pull request by jasonvarga**
This adds `ddd` macros to the Query Builder and Collection classes.
They work just like `dd` but more Ignitiony.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you, but we're not going to merge it. This is probably a bit too opinionated to have in all Laravel installations.

**Comment by vipertecpro** [comment]
Please tell me this 
1. when `ddd()` is removed ? 
2. if someone really really really wanted to use it....Is it achivable on laravel-9 ?
3. i can see `[jasonvarga](https://github.com/jasonvarga) deleted the ddd branch 2 years ago` but i can't find trace of that in changlogs. Can you please update that ?

**Comment by jasonvarga** [comment]
`ddd` was never removed. This was a PR to add it, and was not merged. You could add the macros from this PR into your app's AppServiceProvider.

**Comment by vipertecpro** [comment]
Alright understood, thx alot :D

**Pull request closed without merging**
