### PR TITLE
Ignore JS tests

### LINKED ISSUE #214: Tests being deployed with package
I am using laravel. So I found these tests that are being downloaded with the `ignition` package.

The path of the **tests** are `vendor/facade/ignition/resources/js/stack/__tests__`.

They are just the only tests there in laravel .. are they meant to be shipped with the package?
I am new to this stuff, so just wanted to report it.

### PR DESCRIPTION
**Pull request by JayBizzle**
Fixes #214

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Maybe we should ignore entire `resources/js` and `resources/css` instead?

**Comment by freekmurze** [comment]
I think it's safe to ignore those directories.

**Comment by JayBizzle** [comment]
> Maybe we should ignore entire `resources/js` and `resources/css` instead? Ping @mpociot

Agreed, update the file 👍

**Comment by mpociot** [comment]
Looks good :)

**Pull request merged**
