### PR TITLE
protect post routes with middleware

### PR DESCRIPTION
**Pull request by Gummibeer**
Like discussed with @freekmurze this adds a little protection to the two post routes. In extension of #93

### CODE REVIEW

**Comment by freekmurze** [comment]
Only thing missing here seems to be a test, could you add that @Gummibeer ?

**Comment by Gummibeer** [comment]
Unit or feature?

**Comment by freekmurze** [comment]
Depends what you understand under those terms. I would have a test that sets up a route with the middleware applied to it.

The test would test just make calls to that route.

**Comment by Gummibeer** [comment]
Ok, so feature/implementation. Unittest, for me, would be calling the middleware handle method directly and expect any result.
Will do it tomorrow.

**Comment by freekmurze** [comment]
👍

**Comment by Gummibeer** [comment]
unittests added in https://github.com/facade/ignition/pull/139/commits/c5ded3ea40c9961e87cabc89775c5a2390a51fae

**Comment by freekmurze** [comment]
Thanks for your work on this. 

@mpociot if you agree with these changes too, we can merge them.

**Comment by mpociot** [comment]
Thank you for this! :)

**Pull request merged**
