### PR TITLE
[2.4.*] Fix MakeViewVariableOptionalSolution to disallow stream wrappers and files that do not end in .blade.php

### PR DESCRIPTION
**Pull request by anasmirza534**
I am getting error for passing null value to function that requires string.
previous pull request #356

### CODE REVIEW

**Comment by AlexVanderbist** [comment]
Hey, does this fix a general bug on the latest version or is this something meant for the `2.4.x` branch related to the previous PR? Can you add a test for this too please?

**Comment by anasmirza534** [comment]
Hi there, 

Yes, this pull request is for 2.4.x branch and related to previous PR. 

Also don't upgrade facade/ignition-contracts package for this branch, that required latest version of PHP, I had set version to ` "facade/ignition-contracts": "^1.0.1"`

As requested I added tests and refactor code, hope this could work.

**Comment by AlexVanderbist** [comment]
Hi again! Thanks for adding tests and clarifying. Can you change the PR or recreate it to merge into the 2.4.* branch instead of master? 2.4.* branch is https://github.com/facade/ignition/tree/2.4.x

**Comment by anasmirza534** [comment]
I changed target branch as requested, does this work?

**Comment by freekmurze** [comment]
Closing this due to too much unrelated changes in the PR.

**Pull request closed without merging**
