### PR TITLE
Fix share report route not definded

### LINKED ISSUE #202: Action Facade\Ignition\Http\Controllers\ShareReportController not defined.
# Laravel Version:
 - 6.2.0
# Facade Ignition:
 - 1.6

# Problem:

not showing the UI of the Ignition.
problem with the ignition controller.

image

### PR DESCRIPTION
**Pull request by freekmurze**
Fixes #202

### CODE REVIEW

**Comment by carlobeltrame** [comment]
I added tests for this in #207, please review

**Comment by freekmurze** [comment]
Tests merged into this PR.

**Comment by stevebauman** [comment]
Any update on merging this?

**Comment by joshmurrayeu** [comment]
Any updates?

**Comment by pxpm** [comment]
I can confirm this fixed the issue for me. I got an error in a controller that comes from a service provider loaded before ignition. So when this controller has any error i got the ShareReport not defined. When manually applying this fixes i can see the real error (in controller) that was causing the issue.

**Comment by matthewnessworthy** [comment]
@freekmurze do you have an eta for merging this and tagging a new release?

**Comment by freekmurze** [comment]
Probably early next week

**Comment by mattcroftuk** [comment]
@freekmurze Any further updates on when this is getting tagged?

**Pull request merged**
