### PR TITLE
✨ add support for VScode WSL + SSH remote

### PR DESCRIPTION
**Pull request by tyler36**
This PR adds support for:

- VSCode Remote:WSL
- VSCode Remote:SSH
- VSCode-insiders Remote:WSL
- VSCode-insiders Remote:SSH

## How to use

- Add the following to your project `.env`

```env
IGNITION_EDITOR=vscode-remote
```

- If you prefer to use VSCode-insiders, use `IGNITION_EDITOR=vscode-insiders-remote` instead.

- Next, you need to update your `IGNITION_LOCAL_SITES_PATH` to the following format:

`{remote-type}`+`{remote-target}`/`{remote-path}`

- Pro tip: Run `pwd` from a VSCode terminal when using the remote extension to get the `{remote-path}`

### Remote-WSL

- It is assumed you use VSCode with Remote-WSL extension to manage your project.
- Update your `IGNITION_LOCAL_SITES_PATH` variable to WSL format:
  - `wsl`+`{distro}`/`{remote-path}`

EG. You use a `Ubuntu` WSL2 distro and your project is located at `/home/user13/code/awesome-site`

```env
IGNITION_LOCAL_SITES_PATH=wsl+Ubuntu/home/user13/code/awesome-site
```

### Remote-SSH

- It is assumed you use VSCode with Remote-SSH extension to access your project.
- Update your `IGNITION_LOCAL_SITES_PATH` variable to SSH format:
  - `ssh-remote`+`{host}`/`{remote-path}`

EG. Your SSH file has a Host entry called `devserver` and your project is located at `/home/user13/code/awesome-site`

```env
IGNITION_LOCAL_SITES_PATH=ssh-remote+devserver/home/user13/code/awesome-site
```

### CODE REVIEW

**Comment by tyler36** [comment]
sorry ... the first commit was the compiled file instead of the src.

Not sure if you want both or part of your build process.

**Comment by tyler36** [comment]
fixes #314 ... see https://github.com/facade/ignition/issues/314#issuecomment-832061677

**Comment by freekmurze** [comment]
Could you also PR this to https://github.com/spatie/ignition?

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
