### PR TITLE
Automagically fix missing semicolons, uses tokenization and only suggests with correct linting

### PR DESCRIPTION
**Pull request by MrRio**
# A Solution for Fixing Missing Semicolons

Screen Shot 2019-09-04 at 22 18 53

# How it works

1. First it takes the unexpected token from the error message
2. Then it tokenizes the file in which the syntax error occurred
3. It reverses the order of the tokenization, and loops over to find the unexpected token
4. If then waits until the next whitespace token, and inserts that, THEN a semicolon
5. The file is regenerated in memory with the proposed fix
6. If this in-memory representation of the fix now passes PHP linting, it is offered as a saveable solution

Todo:

- [x] Refactor semicolon insertion slightly
- [x] Add automated tests

### CODE REVIEW

**Comment by MrRio** [comment]
@freekmurze This is all good to review 👍

**Comment by MrRio** [comment]
Have updated with the latest master, tests passing and StyleCI is happy.

**Comment by MrRio** [comment]
CC @freekmurze @mpociot

**Comment by freekmurze** [comment]
Thanks for the PR, we'll review it soon.

**Comment by freekmurze** [comment]
Could you add a test that proves that the `;` is added correctly?

**Comment by freekmurze** [comment]
Closing due to inactivity. Feel free to open a new PR should you want to continue working on this.

**Pull request closed without merging**
